# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='total_comment',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='addr',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='phone',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='desc',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
