# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170425_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, null=True)),
                ('lock', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'crawl_website',
            },
        ),
    ]
